language: ruby
rvm:
  - 2.1.4  # replace this with the ruby version you are using in development
before_script:
  - psql -c 'create database phishbowl_test;' -U postgres
notifications:
  email: false
